// Aca van las constante que se hacen con js
export enum ActionType {
	GET_ALL_EVENT = 'get_all_event',
	SEARCH_EVENT = 'search_event',
	GET_EVENT_ID = 'get_event_id',
	CLEAR_EVENT_ID = 'clear_event_id',
	GET_CATEGORIES = 'get_categories',
	GET_EVENT_BY_CATEGORY = 'get_event_by_category',
	GET_CITIES = 'get_cities',
	PUT_UPDATE_EVENT = 'put_update_event',
	POST_CREATE_CATEGORY = 'post_create_category',
	GET_LOCATIONS = 'get_locations',
	POST_CREATE_EVENT = 'post_create_event',
	DONT_EVENTS = 'dont_events',
	SEARCH_USER = 'search_user',
	GET_FILTER_USER = 'get_filter_user',
	GET_COMMENTS = 'get_comments',
	POST_CREATE_COMMENTS = 'post_create_comments',
	SET_CART_LENGTH = 'SET_CART_LENGTH',
}
